### ISSUE TITLE
Custom CSS is no longer included and the Bible popups don't work anymore

### ISSUE THREAD

**Issue by altwright** [funkydan2/alpha-church#55]
Hi there, I noticed after I pulled down the latest release for _Hugo version > 0.124_ a few months back that my custom CSS and the Bible popups no longer worked. I just tried to rebuild my site from scratch using the instructions in `SETUP.md`, but the same problem persists. I'm currently using Hugo version 0.134 extended. The website I maintain using the theme is [https://gracechristianchurcharmadale.com.au/](https://gracechristianchurcharmadale.com.au/). I had to manually include a link to the custom CSS file in the `header.html` partial since the customCSS parameter doesn't seem to work. I also noticed that the Bible popups don't work in the example site for the latest release either.

**Comment by funkydan2** [comment]
Thanks for reaching out - I think I've worked out the problem.

The problem is with badly configured toml. I've now fixed the example site's configuration to work as it should:

https://github.com/funkydan2/alpha-church/blob/10a4910cd6ed2baf14e1bac45e582525c7a20681/exampleSite/hugo.toml#L88-L100

You need to make sure all the variables (like the bible popups and custom CSS) are listed *before* the [params.author] variables (the need to use the map `params.author` was introduced in a recentish version of hugo).

I hadn't noticed this because I used yaml configuration on my church's website.

If this doesn't work for you—can you link to the sourcecode (git repo) for your church site and I can see if there's anything else going on.

**Comment by altwright** [comment]
Thank you Daniel, that fix shifting the [params.author] variables worked for both the custom CSS and the bible popups in the blog posts. For some reason the bible popups still don't work for me in the sermons though, even though they work in the example site. The bulk of my problems are fixed however.

Thanks.
Ben

Sent with [Proton Mail](https://proton.me/mail/home) secure email.

**Comment by funkydan2** [comment]
Glad it's working. 

With the popups, it is working with sermons...in certain circumstances! So look at https://gracechristianchurcharmadale.com.au/sermons/24_09_15/ and the popup works for the subtitle.

From what I can tell, the popups don't work when referencing a whole chapter (that's why it doesn't work for https://gracechristianchurcharmadale.com.au/sermons/24_09_23-1/) and also not when the reference is in a link or heading.

By the way, I've also fiddled with the podcast XML as I just noticed a problem with Spotify and YouTube for my church (though Apple thinks the feed is fine). If this breaks anything, please open another issue.
